### ISSUE TITLE
calcstess error

### ISSUE THREAD

**Issue by ArneHofemeier** [bernhardw13/BeadSegmentation#7]
Error using calcStress (line 112)
Java exception occurred:
Exception:
	com.comsol.util.exceptions.FlException: The following feature has encountered a problem
Messages:
	The following feature has encountered a problem:
	- Feature: Compile Equations: Stationary (sol1/st1)

	Error in multiphysics compilation.

	/home/comsol/.comsol/v53a/recoveries/MPHRecovery9275date Jul 12 2018 4-27 PM.mph/savepoint1/model.zip (No such
        file or directory)

Stack trace:
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.comsol.model.util.saveload.ZipMphSaver.a(SourceFile:166)
	at com.comsol.model.util.saveload.ZipMphSaver.t(SourceFile:110)
	at com.comsol.model.util.saveload.ZipMphSaver.<init>(SourceFile:90)
	at com.comsol.model.util.saveload.CompleteSavePointSaver.<init>(SourceFile:27)
	at com.comsol.model.util.ModelInternalUtil.storeCompleteSavePointModel(SourceFile:1277)
	at com.comsol.model.util.ModelInternalUtil.storeCompleteSavePointModel(SourceFile:1281)
	at com.comsol.model.dbmodel.ModelDb.storeCompleteSavePointModel(SourceFile:2268)
	at com.comsol.model.method.ModelMethod.createTheSavePoint(SourceFile:1759)
	at com.comsol.model.dbmodel.ModelDb.c(SourceFile:2171)
	at com.comsol.model.dbmodel.ModelDb.b(SourceFile:2151)
	at com.comsol.model.dbmodel.ModelDb.createSavePoint(SourceFile:2137)
	at com.comsol.model.method.ModelMethod.meshextend(SourceFile:523)
	at com.comsol.model.dbmodel.ModelDb.doMeshextend(SourceFile:1122)
	at com.comsol.model.dbmodel.ModelDb.a(SourceFile:1694)
	at com.comsol.model.dbmodel.ModelDb.meshextend(SourceFile:1031)
	at com.comsol.solver.solution.SolverAnalysis.doGenSavePoint(SourceFile:414)
	at com.comsol.solver.solution.SolverAnalysis.a(SourceFile:339)
	at com.comsol.solver.solution.SolverAnalysis.doExecute(SourceFile:199)
	at com.comsol.solver.SolverOperation.execute(SourceFile:217)
	at com.comsol.solver.SolverOperation.addError(SourceFile:454)
	at com.comsol.solver.SolverOperation.execute(SourceFile:221)
	at com.comsol.model.method.SolverSequenceMethod.doRun(SourceFile:2141)
	at com.comsol.model.method.SolverSequenceMethod.doRunAll(SourceFile:2660)
	at com.comsol.model.dbmodel.SolverSequenceDb.runAll(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.comsol.bridge.command.b.a(SourceFile:145)
	at com.comsol.bridge.command.b.run(SourceFile:90)
	at com.comsol.bridge.command.i.execute(SourceFile:42)
	at com.comsol.bridge.command.j.d(SourceFile:711)
	at com.comsol.bridge.command.j.a(SourceFile:699)
	at com.comsol.bridge.command.j$3.a(SourceFile:600)
	at com.comsol.bridge.command.j$3.call(SourceFile:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Error in segmentBeads_v0_1>calcforce_Callback (line 880)
model=calcStress(2100,0.49,1000,r,horzcat(displacementfiles(j).folder,filesep,displacementfiles(j).name),modeltag);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in segmentBeads_v0_1 (line 45)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)segmentBeads_v0_1('calcforce_Callback',hObject,eventdata,guidata(hObject)) 
112 model.sol('sol1').runAll;
The desktop configuration was not saved successfully
java.io.IOException: No space left on device
	at java.io.FileOutputStream.write(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:290)
	at com.mathworks.services.Prefs.savePrefs(Prefs.java:1436)
	at com.mathworks.services.Prefs.save(Prefs.java:633)
	at com.mathworks.services.Prefs$SavePrefsThread.run(Prefs.java:1343)
K>>

**Comment by bernhardw13** [comment]
> java.io.IOException: No space left on device

There was not enough space left on the file system. I cleaned it up, should work now...
